title: "ljf12825's Blog"
description: "Efficient&Elegent"
author:
  name : "Jeff Lee"
  avatar: "assets/images/Avatar.png"
  location: "Unknown"
  links:
   - label: "GitHub"
     icon: "fab fa-github"
     url:  "https://github.com/ljf12825"
   - label: "E-Mail"
     icon: "fas fa-envelope"
     url: "2548278761@qq.com"

remote_theme: "mmistakes/minimal-mistakes@4.27.1"

plugins:
  - jekyll-include-cache

minimal_mistakes_skin: "default"

markdown: kramdown
highlighter: rouge
