title: "ljf12825's Blog"
description: "Efficient & Elegant"
logo: "/assets/images/Avatar.png"

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dark"

author:
  name : "Jeff Lee"
  bio: "Efficient & Elegant"
  avatar: "/assets/images/Avatar.png"
  location: "Unknown"
  email: "2548278761@qq.com"
  links:
  - label: "GitHub"
    icon: "fab fa-github"
    url:  "https://github.com/ljf12825"

reading_time: true

footer:
  links:
  - label: "GitHub"
    icon: "fab fa-github"
    url: "https://githubcoomo/ljf12825"


navigation:
  - title: "Home"
    url: "/"
  - title: "About"
    url: "/about"
  - title: "Blog"
    url: "/blog"
  - title: "ContactMe"
    url: "/contact"


markdown: kramdown
highlighter: rouge
