title: "ljf12825's Blog"
description: "Efficient&Elegent"
logo: "assets/images/Avatar.png"

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-include-cache
minimal_mistakes_skin: "dark"

author:
  name : "Jeff Lee"
  avatar: "/assets/images/Avatar.png"
  location: "Unknown"
  email: "2548278761@qq.com"
  links:
   - label: "GitHub:ljf12825"
     icon: "fab fa-github"
     url:  "https://github.com/ljf12825"

reading_time: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://githubcoomo/ljf12825"

markdown: kramdown
highlighter: rouge
