title: "ljf12825's Blog"

remote_theme: "mmistakes/minimal-mistakes@4.27.1"
plugins:
  - jekyll-include-cache
  - jekyll-remote_theme
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-last-modified-at

description: "Efficient & Elegant"

minimal_mistakes_skin: "dark"

logo: "/assets/images/J.ico"

author:
  name : "Jeff Lee"
  bio: "Efficient & Elegant"
  avatar: "/assets/images/Avatar.png"
  location: "China"
  email: "2548278761@qq.com"
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ljf12825"

collections:
  pages:
    output: true
    permalink: /:path/

reading_time: true
search: true
lunr: 
  search_within_pages: true

toc: true
toc_label: "Content"
toc_sticky: true

footer:
  links:
    - label: "GitHub"
      icon: "fab fa-github"
      url: "https://github.com/ljf12825"

markdown: kramdown
kramdown:
  input: GFM
highlighter: rouge
