baseURL = "https://ljf12825.github.io/"
locale = "en_US"
title = "ljf12825"

[markup]
  [markup.highlight]
    style = "dracula"
    lineNos = false
    noClasses = true
    guessSyntax = true

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

[params]
  codeBase = "../src/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[services]
  [services.rss]
    limit = 20
