baseURL = "https://ljf12825.github.io/"
locale = "en-us"
title = "ljf12825"
enableGitInfo = true

[frontmatter]
  date = ["date", "publishDate", ":default"]
  lastmod = [":git", "lastmod", "fileModTime", ":default"]

[markup]
  [markup.highlight]
    codeFences = true
    style = "dracula"
    lineNos = false
    noClasses = false
    guessSyntax = true

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
  [markup.tableOfContents]
    startLevel = 1
    endLevel = 6
    ordered = false

[params]
  codeBase = "../src/"

[outputs]
  home = ["HTML", "RSS"]
  section = ["HTML", "RSS"]

[services]
  [services.rss]
    limit = 20

[author]
  name = "ljf12825"
  email = "ljf12825@graingen.com"
