baseURL = "https://ljf12825.github.io/"
languageCode = "en-us"
title = "How to Develop a Game"

[markup]
  [markup.highlight]
    style = "monokai"
    lineNos = false
    noClasses = true
    guessSyntax = true

  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true
      
  [markup.tableOfContents]
    startLevel = 1   # 从 h1 开始
    endLevel = 6     # 一直包含到 h6
    ordered = false  # 是否用有序列表