name: Deploy Hugo Site to GitHub Pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          submodules: recursive
          fetch-depth: 0

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v3
        with:
          hugo-version: 'latest'
          extended: true

      - name: Generate build info
        run: |
          mkdir -p data
          
          RAW_VERSION="$(hugo version)"
          
          HUGO_VER=$(echo "$RAW_VERSION" | awk '{print $2}')
          GO_VER=$(echo "$RAW_VERSION" | awk '{print $3}')
          BUILD_PLATFORM=$(echo "$RAW_VERSION" | awk '{print $4}')
          BUILD_DATE=$(echo "$RAW_VERSION" | awk '{print $5}' | cut -d'=' -f2) # 提取日期
          
          echo "build_host: ljf12825.github.io" >> data/build.yaml
          echo "build_time: $(date -u +"%Y-%m-%d %H:%M:%S UTC")" >> data/build.yaml
          
          echo "engine_version: $HUGO_VER" >> data/build.yaml
          echo "engine_platform: $GO_VER" >> data/build.yaml
          echo "engine_compile: $BUILD_PLATFORM" >> data/build.yaml
          echo "engine_build_date: $BUILD_DATE" >> data/build.yaml
          
          echo "commit_full: $GITHUB_SHA" >> data/build.yaml
          echo "commit_short: $(echo $GITHUB_SHA | cut -c1-7)" >> data/build.yaml
          echo "branch: $GITHUB_REF_NAME" >> data/build.yaml
          echo "actor: $GITHUB_ACTOR" >> data/build.yaml
          echo "runner_os: $RUNNER_OS" >> data/build.yaml

      - name: Build with Hugo
        run: hugo --minify

      - name: List public files
        run: ls -la public/

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public

          force_orphan: true

          commit_message: ${{ github.event.head_commit.message }} - Built by Hugo [skip ci]
          user_name: github-actions[bot]
          user_email: 41898282+github-actions[bot]@users.noreply.github.com
